# Generated by Django 4.2.7 on 2023-11-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='end',
        ),
    ]
