# Generated by Django 4.2.7 on 2023-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='business', verbose_name='Фото')),
                ('video', models.ImageField(upload_to='video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Бизнес',
            },
        ),
    ]
