# Generated by Django 4.2.6 on 2023-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_develop'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='video',
            field=models.CharField(default=1, max_length=155, verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
