# Generated by Django 4.2.7 on 2023-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_business_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='ФИО')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Должность')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзывы')),
                ('image', models.ImageField(upload_to='team', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
