# Generated by Django 4.2.6 on 2023-10-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_develop_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовака')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('Довольных клиентов', 'Довольных клиентов'), ('Опытных сотрудников', 'Опытных сотрудников'), ('Уровень удовлетворенности', 'Уровень удовлетворенности'), ('Многолетний опыт', 'Многолетний опыт'), ('Награды', 'Награды')], max_length=155, verbose_name='Выберите иконку')),
                ('title_icon', models.CharField(max_length=155, verbose_name='Процент')),
                ('context_icon', models.CharField(max_length=155, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Достижение',
            },
        ),
    ]
