# Generated by Django 4.2.6 on 2023-10-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('image', models.ImageField(max_length=155, upload_to='', verbose_name='Фото')),
                ('title_imgae', models.CharField(max_length=155, verbose_name='Заголовка Фото')),
                ('context_image', models.CharField(max_length=155, verbose_name='Описание Фото')),
            ],
            options={
                'verbose_name': 'Наша Команда',
            },
        ),
    ]
