# Generated by Django 4.2.7 on 2023-11-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='review',
            field=models.TextField(default=1, verbose_name='Отзывы'),
            preserve_default=False,
        ),
    ]
