# Generated by Django 4.2.6 on 2023-10-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_comand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comand',
            old_name='title_imgae',
            new_name='title_image',
        ),
    ]
