# Generated by Django 4.2.6 on 2023-10-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_klient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('blog_title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('image_blog', models.ImageField(upload_to='requests/', verbose_name='Фото')),
                ('context_blog', models.CharField(max_length=155, verbose_name='Описание Блога')),
                ('blog_text', models.TextField(verbose_name='Текст')),
                ('end_blog', models.CharField(max_length=100, verbose_name='ОТЗЫВ')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Часто Задаваемые Вопросы',
            },
        ),
    ]
