# Generated by Django 4.2.7 on 2023-11-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='service', verbose_name='Фото')),
                ('number_blog', models.CharField(max_length=50, verbose_name='Номер Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Услуги',
            },
        ),
    ]
