# Generated by Django 4.2.7 on 2023-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание')),
                ('title_geografy', models.CharField(max_length=155, verbose_name='Заголовка Географий')),
                ('title_service', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_business', models.CharField(max_length=155, verbose_name='Заголовка Бизнеса')),
                ('description_business', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='service/details', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши примущество',
            },
        ),
    ]
