# Generated by Django 4.2.7 on 2023-11-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.ImageField(upload_to='service/details', verbose_name='Фото 3'),
        ),
    ]
