# Generated by Django 4.2.6 on 2023-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_main_options_main_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Фотография')),
                ('image_title', models.CharField(max_length=100, verbose_name='Заголовка фотографий')),
                ('image_context', models.TextField(verbose_name='Описание фотографий')),
                ('end_image', models.CharField(max_length=100, verbose_name='Конец фотографий')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки Блога',
            },
        ),
    ]
