# Generated by Django 4.2.7 on 2023-11-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='team_kolonki',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Командный Блог'),
        ),
        migrations.AddField(
            model_name='details',
            name='team_kolonki2',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Командный Блог - 2'),
        ),
    ]
