# Generated by Django 4.2.7 on 2023-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_servicedetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='image2',
            field=models.ImageField(default=1, upload_to='service/', verbose_name='Фото 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='image3',
            field=models.ImageField(default=1, upload_to='service/details', verbose_name='Фото 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.ImageField(upload_to='details/', verbose_name='Фото 1'),
        ),
    ]
