# Generated by Django 4.2.7 on 2023-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicedetails_image2_servicedetails_image3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetails',
        ),
    ]
