# Generated by Django 4.2.7 on 2023-11-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_context_text_details_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='context',
            new_name='text',
        ),
    ]
