# Generated by Django 4.2.7 on 2023-11-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_servicedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
