# Generated by Django 4.2.6 on 2023-10-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicetitle_remove_services_context_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetitle',
            options={'verbose_name': '', 'verbose_name_plural': 'Заголовка Блога'},
        ),
    ]
