# Generated by Django 4.2.7 on 2023-11-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_context_details_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='text',
            new_name='context',
        ),
    ]
