# Generated by Django 4.2.6 on 2023-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicetitle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='service_detaild/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Детального Услуги',
            },
        ),
    ]
