# Generated by Django 4.2.6 on 2023-10-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='end_details_main',
            field=models.CharField(default=1, max_length=100, verbose_name='Последняя строка'),
            preserve_default=False,
        ),
    ]
