# Generated by Django 4.2.7 on 2023-11-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_text_details_context'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройка всего Примущество'},
        ),
        migrations.RemoveField(
            model_name='details',
            name='business_blog',
        ),
        migrations.RemoveField(
            model_name='details',
            name='business_context',
        ),
        migrations.RemoveField(
            model_name='details',
            name='business_image',
        ),
        migrations.RemoveField(
            model_name='details',
            name='context',
        ),
        migrations.RemoveField(
            model_name='details',
            name='kolonki',
        ),
        migrations.RemoveField(
            model_name='details',
            name='review_blog',
        ),
        migrations.RemoveField(
            model_name='details',
            name='team_kolonki',
        ),
        migrations.RemoveField(
            model_name='details',
            name='team_kolonki2',
        ),
        migrations.AddField(
            model_name='details',
            name='escort_context',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='escort_image',
            field=models.ImageField(default=1, upload_to='escort', verbose_name='Сопровождение Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='escort_title',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Сопровождение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='geografi_title',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Географий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='geografy_image',
            field=models.ImageField(default=1, upload_to='geografi', verbose_name='Фото Географий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='text',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(default=1, upload_to='service_details', verbose_name='Фото КОманды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='title',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка'),
            preserve_default=False,
        ),
    ]
