# Generated by Django 4.2.7 on 2023-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_details_options_remove_details_business_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=155, verbose_name='Колонки Команды')),
                ('team_title2', models.CharField(max_length=155, verbose_name='Колонки Команды - 2')),
                ('escort_title', models.CharField(max_length=155, verbose_name='Заголовка Сопровождение')),
                ('escort_text', models.CharField(max_length=255, verbose_name='Описание Сопровождение')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Бизнесс и Команда',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='context',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='number_blog',
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Колонка для Географий'),
        ),
    ]
