# Generated by Django 4.2.7 on 2023-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_detailsall_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '', 'verbose_name_plural': 'Наши Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='context',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='number_blog',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер Блога'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовка'),
        ),
    ]
