# Generated by Django 4.2.6 on 2023-10-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('speakers', models.CharField(max_length=255, verbose_name='Колонки')),
                ('image', models.ImageField(upload_to='teamwide/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Широкая География',
            },
        ),
    ]
