# Generated by Django 4.2.7 on 2023-11-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_options_service_context_service_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='context',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='number_blog',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('Стратегическое Консультирование', 'Стратегическое Консультирование'), ('Финансовое Планирование', 'Финансовое Планирование'), ('Достижение Результатов', 'Достижение Результатов'), ('Поддержка На Всех Этапах', 'Поддержка На Всех Этапах')], max_length=50, null=True, verbose_name='Выберите иконку'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Колонки для Консалтинговых Услуг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Колонка для Географий'),
        ),
    ]
