# Generated by Django 4.2.6 on 2023-10-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_consulting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='busines/main', verbose_name='Фотография задниго фона')),
                ('image2', models.ImageField(upload_to='business/', verbose_name='Фотография переднего фона')),
                ('title_blog', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('context_blog', models.CharField(max_length=300, verbose_name='Описание Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Бизнеса',
            },
        ),
    ]
