# Generated by Django 4.2.7 on 2023-11-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_service_options_remove_service_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Колонка для Географий')),
                ('service_title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Колонки для Консалтинговых Услуг')),
                ('icon', models.CharField(blank=True, choices=[('Стратегическое Консультирование', 'Стратегическое Консультирование'), ('Финансовое Планирование', 'Финансовое Планирование'), ('Достижение Результатов', 'Достижение Результатов'), ('Поддержка На Всех Этапах', 'Поддержка На Всех Этапах')], max_length=50, null=True, verbose_name='Выберите иконку')),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '', 'verbose_name_plural': 'Наши Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_title',
        ),
        migrations.AddField(
            model_name='service',
            name='context',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='number_blog',
            field=models.CharField(default=1, max_length=50, verbose_name='Номер Блога'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка'),
            preserve_default=False,
        ),
    ]
