# Generated by Django 4.2.6 on 2023-10-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='image2',
        ),
    ]
