# Generated by Django 4.2.7 on 2023-11-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_servicedetails_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetails',
            options={'verbose_name': '', 'verbose_name_plural': 'География и Услуга'},
        ),
    ]
