# Generated by Django 4.2.6 on 2023-10-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_business_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(default=1, upload_to='service/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
