# Generated by Django 4.2.6 on 2023-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_team_kolonki'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kolonki2',
            field=models.CharField(default=1, max_length=100, verbose_name='Колонки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='kolonki3',
            field=models.CharField(default=1, max_length=100, verbose_name='Колонки'),
            preserve_default=False,
        ),
    ]
