# Generated by Django 4.2.6 on 2023-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('blog_title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('blog_context', models.TextField(verbose_name='Текст Блога')),
                ('icon', models.CharField(choices=[('Локальная Экспертиза, Мировой Опыт', 'Локальная Экспертиза, Мировой Опыт'), ('Преимущество Многокультурного Окружения', 'Преимущество Многокультурного Окружения'), ('Сотрудничество Через Расстояние', 'Сотрудничество Через Расстояние'), ('Мировые Достижения', 'Мировые Достижения'), ('Местное присутствие', 'Местное присутствие'), ('Многогранное понимание культур', 'Многогранное понимание культур')], max_length=155, verbose_name='Выберите Иконку')),
                ('blog_number', models.CharField(max_length=10, verbose_name='Номер Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ВАШ УСПЕХ',
            },
        ),
    ]
