# Generated by Django 4.2.6 on 2023-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='style6/', verbose_name='Фото')),
                ('end', models.CharField(max_length=155, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Стиль 6',
            },
        ),
    ]
