# Generated by Django 4.2.6 on 2023-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('end_contact', models.CharField(max_length=155, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Связаться',
            },
        ),
    ]
