# Generated by Django 4.2.6 on 2023-10-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='end_blog',
            field=models.CharField(default=1, max_length=100, verbose_name='Конец'),
            preserve_default=False,
        ),
    ]
