# Generated by Django 4.2.7 on 2023-11-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriptions_1',
            new_name='descriptions',
        ),
    ]
