# Generated by Django 4.2.6 on 2023-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_main_end_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('text1', models.TextField(verbose_name='Подзаголовок - 1')),
                ('text2', models.TextField(verbose_name='Подзаголовок - 2')),
                ('text3', models.TextField(verbose_name='Подзаголовок - 3')),
                ('text4', models.TextField(verbose_name='Подзаголовок - 4')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Фото')),
                ('end_projectrs', models.CharField(max_length=155, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
