# Generated by Django 4.2.7 on 2023-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_descriptions_1_blog_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
