# Generated by Django 4.2.7 on 2023-11-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ourprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='image',
            field=models.ImageField(default=1, upload_to='project', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
