# Generated by Django 4.2.6 on 2023-11-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='текст')),
                ('kolonki1', models.CharField(max_length=155, verbose_name='1 Колонка')),
                ('kolonki2', models.CharField(max_length=155, verbose_name='2 Колонка')),
                ('kolonki3', models.CharField(max_length=155, verbose_name='3 Колонка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Сопровождение Бизнеса',
            },
        ),
    ]
