# Generated by Django 4.2.7 on 2023-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_ourprojects_descriptio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojects',
            name='descriptio1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер колонки - 1'),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='descriptio2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер колонки - 2'),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='descriptio3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер колонки - 3'),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='descriptio4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер колонки - 4'),
        ),
    ]
