# Generated by Django 4.2.6 on 2023-11-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='teg1',
            field=models.CharField(default=1, max_length=155, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='teg2',
            field=models.CharField(default=1, max_length=155, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='teg3',
            field=models.CharField(default=1, max_length=155, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='teg4',
            field=models.CharField(default=1, max_length=155, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='teg5',
            field=models.CharField(default=11, max_length=155, verbose_name='Теги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='teg_main',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Тегов'),
            preserve_default=False,
        ),
    ]
