# Generated by Django 4.2.7 on 2023-11-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Колонка 1')),
                ('title2', models.CharField(max_length=155, verbose_name='Колонка 2')),
                ('title3', models.CharField(max_length=155, verbose_name='Колонка 3')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Сопровождение Бизнеса',
            },
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
