# Generated by Django 4.2.7 on 2023-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='benefist', verbose_name='Фото')),
                ('icon', models.CharField(choices=[('Локальная Экспертиза, Мировой Опыт', 'Локальная Экспертиза, Мировой Опыт'), ('Преимущество Многокультурного Окружения', 'Преимущество Многокультурного Окружения'), ('Сотрудничество Через Расстояние', 'Сотрудничество Через Расстояние'), ('Мировые Достижения', 'Мировые Достижения'), ('Местное присутствие ', 'Местное присутствие '), ('Многогранное понимание культур ', 'Многогранное понимание культур ')], max_length=155, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Широкая География',
                'verbose_name_plural': 'Широкая География',
            },
        ),
    ]
