# Generated by Django 4.2.7 on 2023-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='range/', verbose_name='Фото')),
                ('icon', models.CharField(choices=[('Стратегическое Консультирование', 'Стратегическое Консультирование'), ('Финансовый Консалтинг', 'Финансовый Консалтинг'), ('Маркетинговые Консультации', 'Маркетинговые Консультации'), ('Поддержка На Всех Этапах', 'Поддержка На Всех Этапах'), ('Достижение Результатов', 'Достижение Результатов'), ('Финансовое Планирование', 'Финансовое Планирование')], max_length=155, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Широкий Спектр',
            },
        ),
    ]
