# Generated by Django 4.2.7 on 2023-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationprocess',
            name='image',
            field=models.ImageField(upload_to='index', verbose_name='Фото'),
        ),
    ]
