# Generated by Django 4.2.7 on 2023-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_operationprocess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(default=1, upload_to='index', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationprocess',
            name='image',
            field=models.ImageField(upload_to='process', verbose_name='фото'),
        ),
    ]
