# Generated by Django 4.2.7 on 2023-11-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_image_alter_operationprocess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationprocess',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер Блога'),
            preserve_default=False,
        ),
    ]
