# Generated by Django 4.2.7 on 2023-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_operationprocess_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriptio',
            field=models.CharField(max_length=355, verbose_name='Описание'),
        ),
    ]
