# Generated by Django 4.2.7 on 2023-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_operationprocess_icon_alter_service_descriptio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=models.CharField(max_length=355, verbose_name='Описание'),
        ),
    ]
