# Generated by Django 4.2.7 on 2023-11-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_benefits_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Контакта'),
            preserve_default=False,
        ),
    ]
