# Generated by Django 4.2.7 on 2023-11-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='limit',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
