# Generated by Django 4.2.7 on 2023-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_contact_limit_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
