# Generated by Django 4.2.7 on 2023-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
