# Generated by Django 4.2.7 on 2023-11-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gellary',
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки главной страницы'},
        ),
    ]
