# Generated by Django 4.2.7 on 2023-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_delete_gellary_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cause',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Причина'),
        ),
    ]
