# Generated by Django 4.2.7 on 2023-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='descriptions',
            field=models.TextField(max_length=255, verbose_name='Описание человека'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_doctor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
