# Generated by Django 4.2.6 on 2023-11-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Щаголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog_title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('blog_context', models.CharField(max_length=255, verbose_name='Описание Блога')),
                ('image_blog', models.ImageField(upload_to='team-details', verbose_name='Фото Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Блога Нашей команды',
            },
        ),
    ]
