# Generated by Django 4.2.6 on 2023-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='blog_context2',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание Блога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='blog_title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка Блога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='image_blog2',
            field=models.ImageField(default=1, upload_to='team-details', verbose_name='Фото Блога'),
            preserve_default=False,
        ),
    ]
