# Generated by Django 4.2.6 on 2023-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_team_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='experience/', verbose_name='Фото')),
                ('kolonki1', models.CharField(max_length=155, verbose_name='Колонка - 1')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наш Опыт',
            },
        ),
    ]
