# Generated by Django 4.2.6 on 2023-11-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='kolonki2',
            field=models.CharField(default=1, max_length=155, verbose_name='Колонка - 2'),
            preserve_default=False,
        ),
    ]
