# Generated by Django 4.2.6 on 2023-11-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_experience_kolonki2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('text', models.CharField(max_length=255, verbose_name='Конец')),
                ('end', models.CharField(max_length=155, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Связатьс с нами',
            },
        ),
    ]
