# Generated by Django 4.2.6 on 2023-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='pricind/', verbose_name='Фото')),
                ('end', models.CharField(max_length=155, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ценообразование',
            },
        ),
    ]
