# Generated by Django 4.2.6 on 2023-11-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricind', '0002_escort'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='image',
            field=models.ImageField(default=1, upload_to='escort/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escort',
            name='context_blog',
            field=models.CharField(max_length=300, verbose_name='Описание Блога'),
        ),
    ]
