# Generated by Django 4.2.6 on 2023-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricind', '0003_escort_image_alter_escort_context_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='image',
        ),
    ]
