# Generated by Django 4.2.6 on 2023-11-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricind', '0004_remove_escort_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('context_title', models.CharField(max_length=255, verbose_name='Заголовка описание')),
                ('blogtitle', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('blogcontext', models.CharField(max_length=30, verbose_name='Описание Блога')),
            ],
        ),
    ]
