# Generated by Django 4.2.6 on 2023-11-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricind', '0005_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Часто Задаваемые вопросы', 'verbose_name_plural': 'Часто Задаваемые вопросы'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='blogcontext',
            field=models.TextField(verbose_name='Описание Блога'),
        ),
    ]
