# Generated by Django 4.2.6 on 2023-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricind', '0006_alter_questions_options_alter_questions_blogcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('blog_context', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Часто Задаваемые вопросы 2 Блог',
            },
        ),
    ]
