# Generated by Django 4.2.6 on 2023-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=155, verbose_name='Заголвка - 1')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголвка - 2')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголвка - 3')),
                ('image_main', models.ImageField(upload_to='main', verbose_name='Фото большое')),
                ('image', models.ImageField(upload_to='galerry', verbose_name='Фото маленький')),
                ('context', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка глвной строницы',
            },
        ),
    ]
