# Generated by Django 4.2.6 on 2023-10-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title3',
        ),
    ]
