# Generated by Django 4.2.6 on 2023-10-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title2_remove_post_title3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=355, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='job', verbose_name='Фотография работы')),
                ('image_title', models.CharField(max_length=100, verbose_name='Заголвка фотографий')),
                ('image_context', models.CharField(max_length=300, verbose_name='Описание фотографий')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки работы',
            },
        ),
    ]
