# Generated by Django 4.2.6 on 2023-10-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_jobs_remove_job_context_remove_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.CharField(default=1, max_length=1, verbose_name='Номер работы'),
            preserve_default=False,
        ),
    ]
