# Generated by Django 4.2.6 on 2023-10-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_job_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка О нас')),
                ('context', models.CharField(max_length=155, verbose_name='Описание о нас')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image_main', models.ImageField(upload_to='about', verbose_name='Фото')),
                ('image', models.ImageField(upload_to='about/main', verbose_name='Задний фотография')),
                ('endabout', models.CharField(max_length=55, verbose_name='конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'О Нас',
            },
        ),
    ]
