# Generated by Django 4.2.6 on 2023-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_main_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Min_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/main', verbose_name='Задний фотография')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Задний фотография',
            },
        ),
        migrations.RemoveField(
            model_name='main_about',
            name='image',
        ),
    ]
