# Generated by Django 4.2.6 on 2023-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_min_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('context', models.CharField(max_length=300, verbose_name='Описание Блога')),
                ('end_blog', models.CharField(max_length=50, verbose_name='Конец Блога')),
            ],
        ),
        migrations.CreateModel(
            name='Direction_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=50, verbose_name='Заголовка')),
                ('context_main', models.CharField(max_length=100, verbose_name='Описание')),
            ],
        ),
    ]
