# Generated by Django 4.2.6 on 2023-10-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_direction_direction_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки Направление'},
        ),
        migrations.AddField(
            model_name='job',
            name='icon',
            field=models.CharField(choices=[('Разработка', 'Разработка'), ('Изучение', 'Изучение'), ('Запуск', 'Запуск')], default=1, max_length=155, verbose_name='Выберите иконку'),
            preserve_default=False,
        ),
    ]
