# Generated by Django 4.2.6 on 2023-10-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_direction_options_job_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('more_details1', models.CharField(max_length=155, verbose_name='Загаловка')),
                ('more_details_text1', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Преимущества',
            },
        ),
    ]
