# Generated by Django 4.2.6 on 2023-10-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='more_details2',
            field=models.CharField(default=1, max_length=155, verbose_name='Загаловка - 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantages',
            name='more_details3',
            field=models.CharField(default=1, max_length=155, verbose_name='Загаловка - 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantages',
            name='more_details4',
            field=models.CharField(default=1, max_length=155, verbose_name='Загаловка - 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantages',
            name='more_details_text2',
            field=models.TextField(default=1, verbose_name='Описание - 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantages',
            name='more_details_text3',
            field=models.TextField(default=1, verbose_name='Описание - 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantages',
            name='more_details_text4',
            field=models.TextField(default=1, verbose_name='Описание - 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantages',
            name='more_details1',
            field=models.CharField(max_length=155, verbose_name='Загаловка - 1'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='more_details_text1',
            field=models.TextField(verbose_name='Описание - 1'),
        ),
    ]
