# Generated by Django 4.2.6 on 2023-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_advantages_more_details2_advantages_more_details3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка  Наши Преимущество',
            },
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='context',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='text',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='title',
        ),
    ]
