# Generated by Django 4.2.6 on 2023-10-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_advantages_more_details4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantages',
            name='more_details2',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='more_details3',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='more_details_text2',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='more_details_text3',
        ),
    ]
