# Generated by Django 4.2.6 on 2023-10-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_advantages_more_details2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advantage/', verbose_name='Фото')),
                ('title', models.CharField(max_length=1, verbose_name='заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотграфия Преимущество',
            },
        ),
    ]
