# Generated by Django 4.2.6 on 2023-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_imageadvantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='Отценка')),
                ('context1', models.CharField(max_length=100, verbose_name='Довольных Клиенты')),
                ('grade2', models.CharField(max_length=50, verbose_name='Отценка')),
                ('context2', models.CharField(max_length=100, verbose_name='Опытных сотрудников')),
                ('grade3', models.CharField(max_length=50, verbose_name='Отценка')),
                ('context3', models.CharField(max_length=100, verbose_name='Удовлетворенности')),
                ('grade4', models.CharField(max_length=50, verbose_name='Отценка')),
                ('context4', models.CharField(max_length=100, verbose_name='Наград')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки Процентов Клиентов',
            },
        ),
        migrations.AlterModelOptions(
            name='imageadvantage',
            options={'verbose_name': '', 'verbose_name_plural': 'Фотография Преимущество'},
        ),
    ]
