# Generated by Django 4.2.6 on 2023-10-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_status_alter_imageadvantage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='context2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='context3',
        ),
        migrations.RemoveField(
            model_name='status',
            name='context4',
        ),
        migrations.RemoveField(
            model_name='status',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='grade3',
        ),
        migrations.RemoveField(
            model_name='status',
            name='grade4',
        ),
    ]
