# Generated by Django 4.2.6 on 2023-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_status_status_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(default=1, upload_to='status', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
