# Generated by Django 4.2.6 on 2023-10-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_status_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='image',
        ),
    ]
