# Generated by Django 4.2.6 on 2023-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_status_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=True, verbose_name='Фото справа')),
                ('image2', models.ImageField(upload_to=True, verbose_name='Фото слева')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Заголовка Заявки',
            },
        ),
    ]
