# Generated by Django 4.2.6 on 2023-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_application_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image2',
            field=models.ImageField(default=11, upload_to=True, verbose_name='Фото слева'),
            preserve_default=False,
        ),
    ]
