# Generated by Django 4.2.6 on 2023-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_application_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('addres', models.CharField(max_length=100, verbose_name='Адресс')),
                ('limit', models.CharField(max_length=155, verbose_name='Лимит')),
                ('choise', models.CharField(max_length=155, verbose_name='Выбор значение')),
                ('end', models.CharField(max_length=50, verbose_name='Отправка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Заявки',
            },
        ),
    ]
