# Generated by Django 4.2.6 on 2023-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='percent',
            field=models.CharField(default=1, max_length=100, verbose_name='Процент'),
            preserve_default=False,
        ),
    ]
