# Generated by Django 4.2.6 on 2023-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_applications_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Заголовка Отделов',
            },
        ),
    ]
