# Generated by Django 4.2.6 on 2023-10-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_applicati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='title',
        ),
    ]
