# Generated by Django 4.2.6 on 2023-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_applications_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Фото')),
                ('end', models.CharField(max_length=100, verbose_name='Конец')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Клиенты',
            },
        ),
    ]
