# Generated by Django 4.2.6 on 2023-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Фото')),
                ('title', models.CharField(max_length=100, verbose_name='Не важно')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотография Клиентов',
            },
        ),
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
    ]
