# Generated by Django 4.2.6 on 2023-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Фото')),
                ('title', models.CharField(max_length=100, verbose_name='Не важно')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотография Клиентов',
            },
        ),
        migrations.CreateModel(
            name='Foote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context1', models.CharField(max_length=255, verbose_name='Подзаголовок 1 Услуги')),
                ('context2', models.CharField(max_length=255, verbose_name='Подзаголовок 2 Услуги')),
                ('context3', models.CharField(max_length=255, verbose_name='Подзаголовок 3 Услуги')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Подзаголовок Услуги',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка - 1')),
                ('title2', models.CharField(max_length=150, verbose_name='Заголовок - 2')),
                ('title3', models.CharField(max_length=150, verbose_name='Заголовок - 3')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
    ]
