# Generated by Django 4.2.6 on 2023-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_client_foote_footer_remove_clients_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction_main',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки Главной Направление'},
        ),
        migrations.RemoveField(
            model_name='foote',
            name='context3',
        ),
        migrations.AddField(
            model_name='foote',
            name='mage',
            field=models.ImageField(default=1, upload_to='footer', verbose_name='Конец Footer'),
            preserve_default=False,
        ),
    ]
