# Generated by Django 4.2.6 on 2023-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_client_remove_clients_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=100, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
