# Generated by Django 4.2.6 on 2023-10-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_direction_main_options_remove_foote_context3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foote',
            old_name='mage',
            new_name='image',
        ),
    ]
