# Generated by Django 4.2.6 on 2023-10-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=255, verbose_name='Подзаголовок Услуги')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Подзаголовок Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='footer',
            name='context',
        ),
    ]
