# Generated by Django 4.2.6 on 2023-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_foote_remove_footer_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='foote',
            name='context2',
            field=models.CharField(default=1, max_length=255, verbose_name='Подзаголовок Услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foote',
            name='context3',
            field=models.CharField(default=1, max_length=255, verbose_name='Подзаголовок Услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='title2',
            field=models.CharField(default=1, max_length=150, verbose_name='Заголовок - 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='title3',
            field=models.CharField(default=1, max_length=150, verbose_name='Заголовок - 3'),
            preserve_default=False,
        ),
    ]
