# Generated by Django 4.2.6 on 2023-10-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_rename_mage_foote_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='title',
            new_name='title1',
        ),
    ]
