# Generated by Django 4.2.6 on 2023-10-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_rename_title_footer_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=50, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='main/', verbose_name='Фотография')),
                ('image2', models.ImageField(upload_to='main/', verbose_name='Фотография заднего фона')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Главная строница',
            },
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Advantages',
        ),
        migrations.DeleteModel(
            name='Applicati',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Direction_Main',
        ),
        migrations.DeleteModel(
            name='Foote',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='ImageAdvantage',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Main_About',
        ),
        migrations.DeleteModel(
            name='Min_About',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
