# Generated by Django 4.2.6 on 2023-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_remove_foote_context3_foote_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foote',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Фото футера'),
        ),
    ]
