# Generated by Django 4.2.6 on 2023-10-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_main_delete_advantage_delete_advantages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='job/', verbose_name='Фотография')),
                ('image_title', models.CharField(max_length=155, verbose_name='Заголовка блога')),
                ('image_context', models.CharField(max_length=255, verbose_name='Описание блога')),
                ('number', models.CharField(choices=[('Изучение', 'Изучение'), ('РАЗРАБОТКА', 'РАЗРАБОТКА'), ('ЗАПУСК', 'ЗАПУСК')], max_length=20, verbose_name='Выберите иконку и номер блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Блога',
            },
        ),
    ]
