# Generated by Django 4.2.6 on 2023-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_foote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foote',
            name='image',
        ),
        migrations.AddField(
            model_name='foote',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
