# Generated by Django 4.2.6 on 2023-10-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='number',
        ),
        migrations.AddField(
            model_name='job',
            name='icon',
            field=models.CharField(choices=[('Изучение', 'Изучение'), ('РАЗРАБОТКА', 'РАЗРАБОТКА'), ('ЗАПУСК', 'ЗАПУСК')], default=1, max_length=20, verbose_name='Выберите иконку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='num',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер блога'),
            preserve_default=False,
        ),
    ]
