# Generated by Django 4.2.6 on 2023-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_remove_job_number_job_icon_job_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about/main', verbose_name='Фотография переденго фона')),
                ('image2', models.ImageField(upload_to='about/', verbose_name='Фотография заднего фона')),
                ('text', models.TextField(verbose_name='Текст')),
                ('end_about', models.CharField(max_length=50, verbose_name='Читать далее')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
