# Generated by Django 4.2.6 on 2023-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('blog_title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('blog_context', models.TextField(verbose_name='Описание Блога')),
                ('end_blog', models.CharField(max_length=50, verbose_name='Конец Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Натсройка Напрвление',
            },
        ),
    ]
