# Generated by Django 4.2.6 on 2023-10-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='advantages/', verbose_name='Фото')),
                ('informations_title', models.CharField(max_length=155, verbose_name='Заголовка Блога')),
                ('informations_context', models.TextField(verbose_name='Описание Блога')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши преимушество',
            },
        ),
    ]
