# Generated by Django 4.2.6 on 2023-10-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='image2',
            field=models.ImageField(default=1, upload_to='advantages/', verbose_name='Фото 2'),
            preserve_default=False,
        ),
    ]
