# Generated by Django 4.2.6 on 2023-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_advantages_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=50, verbose_name='Процент')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Описание',
            },
        ),
    ]
