# Generated by Django 4.2.6 on 2023-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(default=1, upload_to='description/'),
            preserve_default=False,
        ),
    ]
