# Generated by Django 4.2.6 on 2023-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='icon',
            field=models.CharField(choices=[('Довольных клиентов', 'Довольных клиентов'), ('Опытных сотрудников', 'Опытных сотрудников'), ('Удовлетворенности', 'Удовлетворенности'), ('Наград', 'Наград')], default=1, max_length=50, verbose_name='Выберите иконку'),
            preserve_default=False,
        ),
    ]
