# Generated by Django 4.2.6 on 2023-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_description_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('cotext', models.CharField(max_length=155, verbose_name='Описание')),
                ('speakers', models.CharField(max_length=50, verbose_name='Заголовок калонки')),
                ('image', models.ImageField(upload_to='speakers/', verbose_name='Фото')),
                ('frist_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('addres_email', models.CharField(max_length=100, verbose_name='Google Аккаунт')),
                ('limit', models.CharField(max_length=100, verbose_name='Лимит бюджета')),
                ('meaning_main', models.CharField(max_length=100, verbose_name='Значение')),
                ('meaning', models.CharField(max_length=155, verbose_name='Процент значени')),
                ('end_application', models.CharField(max_length=50, verbose_name='Конец заявки')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Заявки',
            },
        ),
    ]
