# Generated by Django 4.2.6 on 2023-10-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cotext',
            new_name='coтtext',
        ),
    ]
