# Generated by Django 4.2.6 on 2023-10-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_rename_cotext_application_coтtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='coтtext',
            new_name='context',
        ),
    ]
