# Generated by Django 4.2.6 on 2023-10-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_rename_coтtext_application_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image2',
            field=models.ImageField(default=1, upload_to='application/', verbose_name='Фотография - 2'),
            preserve_default=False,
        ),
    ]
